### ISSUE TITLE
Partie introductive

### ISSUE THREAD

**Issue by benel** [UTT-GL03/Timy#1]
Merci pour la présentation de votre sujet, son utilité sociale, ses impacts numériques.

Sur le fond, il pourrait être intéressant de chiffrer l'empreinte d'un agenda papier. Vous ne la trouverez probablement pas pour un agenda proprement dit, mais peut-être pouvez-vous la rapprocher de celle d'un cahier ou d'un livre (avec un poids ou un nombre de pages équivalent). Prenez en compte également le nombre de fois où il sera consulté dans une année.

Sur la forme : 
- il y a de nombreuses erreurs d'accord,
- quelques coquilles,
- pensez à mettre le lien vers la source que vous indiquez.

Merci d'avance.

**Comment by benel** [comment]
@margote15 @ayoub77200 
N'hésitez pas à commenter le ticket pour indiquer où vous en êtes de la prise en compte des remarques.

**Comment by margote15** [comment]
Bonjour, nous avons pris en compte les remarques.

**Comment by benel** [comment]
Merci @margote15 et @ayoub77200.

> pensez à mettre le lien vers la source que vous indiquez.

Voici la syntaxe en Markdown pour faire un lien :

```markdown
[ancre](lien)
```

**Comment by margote15** [comment]
Merci, c'est corrigé
