### ISSUE TITLE
Résultats de l'impact des scénarios

### ISSUE THREAD

**Issue by benel** [UTT-GL03/Timy#2]
Merci pour vos résultats. C'est assez impressionnant comme rendu sachant que vous avez fait le tableau (et les mesures) à la main.

Pensez à introduire et à référencer vos résultats dans le README. Expliquez en particulier la conception de votre scénario. Ça pourrait être une bonne idée de commenter aussi ce qui ressort de vos résultats.

**Comment by margote15** [comment]
Bonjour, votre commentaire a été pris en compte.
