### ISSUE TITLE
Impact de l'agenda papier

### ISSUE THREAD

**Issue by benel** [UTT-GL03/Timy#3]
> génère entre 1,3 et 7,5 kg d’équivalent CO₂ (...)
> L’impact écologique d’un agenda papier est amorti par son usage quotidien et prolongé sur une année, ce qui optimise l’empreinte liée à sa production.

Merci @margote15 et @ayoub77200.

C'est intéressant et ça mériterait un petit calcul : si on considère 
un impact intermédiaire de 4 kg pour l'agenda sur papier et plutôt un usage professionnel (donc environ 200 jours par an), on arrive à un impact par journée d'usage de 20g. 
Si on consulte plus de 10 fois un agenda numérique avec un impact de 2g ou plus, l'agenda numérique a alors plus d'impact que l'agenda papier. Adaptez le calcul si nécessaire, mais ce serait bien de faire apparaître un calcul de ce type. Car on voit que suivant la fréquence d'usage la balance pèsera plutôt du côté numérique ou du côté du papier.

Par ailleurs comme l'avantage du numérique est un peu "érodé" par ce qui précède, vous devriez mentionner aussi les calendriers partagés (par une équipe de travail, un couple, etc.) qui donne une réelle raison d'avoir une application Web (plutôt qu'une application monoposte).
Sur l'intérêt d'une application connectée également, vous pourriez mentionner la synchronisation entre ordinateur et smartphone.

**Comment by margote15** [comment]
Bonjour, votre commentaire a été pris en compte.
