### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by benel** [UTT-GL03/Timy#5]
Merci pour le compte-rendu de votre prototypage, @ayoub77200 et @margote15.
Voici quelques points d'amélioration...

> Scheduele-X 

Coquille.

> Cette bibliothèque nous permet de réaliser un calendrier sans utiliser de fichier CSS (ce qui permet potentiellement de réduire le nombre de requêtes et donc de charger plus rapidement les pages).

Un peu risqué comme argument : 
- le CSS est souvent moins efficace que le javascript, 
- par ailleurs êtes-vous certains qu'il n'y ait pas de CSS à l'intérieur ?
- en nombre de requêtes ça n'aurait rien changé puisque tous les CSS sont concaténés.

Je pense qu'il faudrait surtout dire qu'au départ vous l'avez adopté par facilité, en espérant que ça n'aurait pas trop d'impact (ce qui s'est confirmé ensuite). 

> nous rencontrons un problème d’affichage des numéros des jours.

Vous n'avez toujours pas réussi à corriger votre problème d'affichage ?

>  Cette analyse a été réalisée dans deux modes : "développement" et "pré-production".

Il faut peut-être expliciter pourquoi vous avez testé aussi en mode développement (alors qu'évidemment seul le mode pré-production nous intéresse vraiment).
D'ailleurs, comme le but était "pédagogique" inutile de mesurer encore le mode développement dans les versions suivantes des prototypes. 

> Or, GreenFrame n'a pas la capacité de se connecter et se contente donc d'analyser uniquement les pages de connexion. 

Ce n'est pas tout à fait exact. 
Il est vrai que quand l'analyse est démarrée à travers l'interface Web (mode "single page"), le scénario est imposé et qu'il s'agit d'une simple consultation de la page.
Par contre, avec l'interface en ligne de commande, on peut créer son propre scénario Playwright. Mais comme la synchronisation des actions s'est révélée très difficile, je ne vous ai pas recommandé de le faire.
Par ailleurs, l'utilisation de mots de passe personnels requiert pas mal d'efforts si on veut éviter une fuite de données.

> Nous utiliserons désormais un autre logiciel, GreenFrame

La transition avec ce qui précède est étrange. Il faudrait reformuler un peu...

> données statistiques

statistiques ou statiques ?

Merci d'avance.

**Comment by ayoub77200** [comment]
Bonjour, nous avons pris en compte vos remarques et effectuer les changements,
